name: Automatic Data Preprocessing

on:
  push: # Trigger workflow setiap kali ada push ke repository
    branches: [ main ] # Hanya untuk branch 'main' (sesuaikan jika nama branch Anda beda)
  pull_request: # Trigger juga saat ada pull request ke branch 'main'
    branches: [ main ]
  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual dari tab Actions

jobs:
  preprocess:
    runs-on: ubuntu-latest # Menggunakan runner Ubuntu terbaru

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Langkah untuk mengambil kode dari repository

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9' # Tentukan versi Python (sesuaikan jika perlu)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy requests scikit-learn # Install library yang dibutuhkan skrip

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_MFauzanFachruziRauf.py # Jalankan skrip Anda
      # Pastikan path ke skrip ini benar dari root repository

    - name: Commit and push processed data (jika ada perubahan)
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add preprocessing/namadataset_preprocessing/bitcoin_idr_daily_processed.csv # Path ke file output
        # Cek apakah ada perubahan untuk di-commit
        if ! git diff --staged --quiet; then
          git commit -m "GitHub Actions: Update processed dataset"
          git push
        else
          echo "No changes to commit in processed data."
        fi
