name: Automatic Data Preprocessing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    # Tambahkan baris permissions di sini:
    permissions:
      contents: write # Memberikan izin tulis untuk konten repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy requests scikit-learn

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_MFauzanFachruziRauf.py

    - name: Commit and push processed data (jika ada perubahan)
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add preprocessing/namadataset_preprocessing/bitcoin_idr_daily_processed.csv
        if ! git diff --staged --quiet; then
          git commit -m "GitHub Actions: Update processed dataset"
          git push
        else
          echo "No changes to commit in processed data."
        fi
